name: flutter_application_4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_riverpod: ^2.4.0
  
  # HTTP Client
  dio: ^5.4.0
  
  # Routing
  go_router: ^13.0.0
  
  # Code Generation (optional but recommended)
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  url_launcher: ^6.3.2
  sembast: ^3.8.5+1
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
